### PR TITLE
Issue #32 Implemented Insert method 

### PR DESCRIPTION
**Pull request by deepigarg**
Implemented insert method along with tests

### CODE REVIEW

**Comment by rubydesign** [comment]
@deepigarg a good start, and since you have good coverage we know it works.

There is a couple of things i need you to do though:
- indentation of the code should be 2 spaces
- the tests need to be broken into 3 separate tests (one for each assert, so if something breaks, one can see immediately what)
- method calls without args don't usually have () in ruby (at least in ruby-x)
- `self.` is python style, in ruby usually omitted unless necessary 

I would suggest you challenge yourself and whittle some lines off that code. Since i have not coded this i can not say for sure, but it looks verbose. I suggest you can do with one index in each loop. And the first loop is a sort of copy, that could be a separate method. (Usually methods in good ruby are not longer than 5-8 lines). But i'll accept the pull with just the first changes if you don't feel like it.

**Comment by deepigarg** [comment]
> @deepigarg a good start, and since you have good coverage we know it works.
> 
> There is a couple of things i need you to do though:
> 
> * indentation of the code should be 2 spaces
> * the tests need to be broken into 3 separate tests (one for each assert, so if something breaks, one can see immediately what)
> * method calls without args don't usually have () in ruby (at least in ruby-x)
> * `self.` is python style, in ruby usually omitted unless necessary
> 
> I would suggest you challenge yourself and whittle some lines off that code. Since i have not coded this i can not say for sure, but it looks verbose. I suggest you can do with one index in each loop. And the first loop is a sort of copy, that could be a separate method. (Usually methods in good ruby are not longer than 5-8 lines). But i'll accept the pull with just the first changes if you don't feel like it.

Hey!
I agree that the code could have been much smaller, but the '+' operation or [] method have not yet been defined for Word, and thus I had to code it like this. Kindly guide me on how to reduce the code without the use of these two methods.

**Comment by rubydesign** [comment]
Can you just fix the conflicts (pull and merge)
and make the formatting changes.

I can show you then after i have accepted the PR

**Comment by rubydesign** [comment]
Congrats, you landed your first PR.
I'll try and change the method today, maybe have a look tomorrow.

**Comment by rubydesign** [comment]
Btw, do you know what a topic-branch is? try and google it if not. Those can be useful, and neccessary for larger changes

**Comment by deepigarg** [comment]
Thanks a lot for guiding me!
Will surely look into it.

**Comment by rubydesign** [comment]
I fixed the method, i hope you don't take offence. It really was not by design. It's just when i code, i code in the way i do, so that is what happened.

I hope you can see the benefit:
- reusable code was created as a helper method (copy_to_from)
- code is more readable (the copyXX expresses intention, whereas the while was "just doing it")
- overall naming is more intuitive.
- methods are shorter (more readable)

Like i said, don't take this to mean you wrote bad code. For me it's just habit after 30 years.

PS, i forgot to say. In future you can write copy , not cpy , and index , not ind. (I hope you have auto-complete too)

**Pull request merged**
